version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: competition_vault
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  indexer:
    build: 
      context: ./indexer
      dockerfile: Dockerfile
    command: pnpm run start:dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/competition_vault
      PORT: 3000
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./indexer:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db_data: 