version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: competition_vault
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  indexer:
    build: 
      context: ./indexer
      dockerfile: Dockerfile
    command: pnpm run start:dev
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/competition_vault
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./indexer:/app
      - /app/node_modules
    restart: unless-stopped
    network_mode: host

volumes:
  postgres_data: 