/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Button, ButtonInterface } from "../Button";

const _abi = [
  {
    type: "function",
    name: "lastPressTime",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pressButton",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ButtonPressed",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506103968061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063b9dd185e14610038578063c8b5da6614610068575b5f5ffd5b610052600480360381019061004d9190610206565b610072565b60405161005f9190610249565b60405180910390f35b610070610086565b005b5f602052805f5260405f205f915090505481565b5f429050610e105f5f3373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f20546100d4919061028f565b811015610116576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161010d90610342565b60405180910390fd5b805f5f3373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f20819055503373ffffffffffffffffffffffffffffffffffffffff167ff1e2abbdd3969fea5f6950e78b803559d0587ff8da184624bdba51665307c1618260405161019d9190610249565b60405180910390a250565b5f5ffd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f6101d5826101ac565b9050919050565b6101e5816101cb565b81146101ef575f5ffd5b50565b5f81359050610200816101dc565b92915050565b5f6020828403121561021b5761021a6101a8565b5b5f610228848285016101f2565b91505092915050565b5f819050919050565b61024381610231565b82525050565b5f60208201905061025c5f83018461023a565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f61029982610231565b91506102a483610231565b92508282019050808211156102bc576102bb610262565b5b92915050565b5f82825260208201905092915050565b7f43616e206f6e6c7920707265737320627574746f6e206f6e63652070657220685f8201527f6f75720000000000000000000000000000000000000000000000000000000000602082015250565b5f61032c6023836102c2565b9150610337826102d2565b604082019050919050565b5f6020820190508181035f83015261035981610320565b905091905056fea264697066735822122073b0950cd840a5e2fbcc69d8e9fef6055cd2501c3d0447d94d6f842d905be95064736f6c634300081b0033";

type ButtonConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ButtonConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Button__factory extends ContractFactory {
  constructor(...args: ButtonConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Button & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Button__factory {
    return super.connect(runner) as Button__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ButtonInterface {
    return new Interface(_abi) as ButtonInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Button {
    return new Contract(address, _abi, runner) as unknown as Button;
  }
}
