name: Contracts CI

on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        with:
          version: 8.15.4

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint commits
        run: npx commitlint --from=HEAD~1 --to=HEAD

  build-and-test:
    needs: lint-commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        with:
          version: 8.15.4

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
        with:
          version: stable

      - name: Install npm dependencies
        working-directory: contracts
        run: pnpm install

      - name: Install Foundry dependencies
        working-directory: contracts
        run: |
          forge install
          forge install transmissions11/solmate
          forge install OpenZeppelin/openzeppelin-contracts

      - name: Build contracts
        working-directory: contracts
        run: forge build

      - name: Run tests
        working-directory: contracts
        run: forge test -vv 