name: Contracts CI

on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts-ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - '.husky/**'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts-ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - '.husky/**'

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint commits
        run: pnpm commitlint --from=HEAD~1 --to=HEAD

  build-and-test:
    needs: lint-commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Install dependencies
        working-directory: contracts
        run: forge install

      - name: Build contracts
        working-directory: contracts
        run: forge build

      - name: Run tests
        working-directory: contracts
        run: forge test -vv 