name: Contracts CI

on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts-ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - '.husky/**'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts-ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - '.husky/**'

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint commits
        run: npx commitlint --from=HEAD~1

  build-and-test:
    needs: lint-commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Install dependencies
        working-directory: contracts
        run: forge install

      - name: Build contracts
        working-directory: contracts
        run: forge build

      - name: Run tests
        working-directory: contracts
        run: forge test -vv 