name: Indexer CI

on:
  push:
    paths:
      - 'indexer/**'
      - '.github/workflows/indexer-ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - '.husky/**'
  pull_request:
    paths:
      - 'indexer/**'
      - '.github/workflows/indexer-ci.yml'
      - 'commitlint.config.js'
      - 'package.json'
      - '.husky/**'

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint commits
        run: npx commitlint --from=HEAD~1 --to=HEAD

  build-and-test:
    needs: lint-commits
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: indexer
        run: pnpm install

      - name: Build
        working-directory: indexer
        run: pnpm build

      - name: Run tests
        working-directory: indexer
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: pnpm test 